# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Download Dependencies
      run: go get github.com/bwmarrin/discordgo@v0.27.1
          go get github.com/joho/godotenv@v1.5.1
          go get github.com/sirupsen/logrus@v1.9.3
          go get gorm.io/driver/sqlite@v1.5.5
          go get gorm.io/gorm@v1.25.7

    - name: Build
      run: go build .
