# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Build Bot
      run: go build -o CODStatusBot .

    - name: Build Dashboard
      run: go build -o CODStatusDash ./codstatusadmin/.


    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CODStatusBot
        path: ./CODStatusBot

        name: CODStatusDash
        path: ./codstatusadmin


    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./CODStatusBot
        asset_name: CODStatusBot
        asset_path: ./codstatusadmin
        asset_name: CODStatusDash
        asset_content_type: application/octet-stream
        
