name: Build

on:
  release:
    types: [created]

jobs:
  build-linux-amd64:
    name: Build Linux/AMD64
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Build Binaries
        uses: lmangani/go-release-action@v1.37-ubuntu
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          goos: linux
          goarch: amd64
          goversion: 1.22.0
          project_path: .
          binary_name: sbchecker
          build_flags: -buildvcs=false
      
      - name: Add Directories and Files
        run: |
          mkdir -p internal models cmd logs
          # Copy directories recursively
          cp -r path/to/internal/* internal/
          cp -r path/to/models/* models/
          cp -r path/to/cmd/* cmd/
          cp -r path/to/logs/* logs/
          cp path/to/main.go .
          cp path/to/.env .
          cp path/to/start.sh .

      - name: Package Directories and Files
        uses: actions/upload-artifact@v2
        with:
          name: extra-directories-files
          path: internal models cmd logs main.go .env start.sh
